name: CMS
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: windows-latest
    env:
      nodeVersion: 'lts/*'
      artifactName: production-files
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}

  #    - name: Install Build Tools for Node.js
   #      run: npm install -g windows-build-tools

      - name: Install PM2
        run: npm install pm2 -g

    #  - name: Download production files
    #   uses: actions/download-artifact@v3
    #    with:
    #      name: production-files
     #     path: D:\a\Cms_New_Script_Arizon\Cms_New_Script_Arizon
    
      - name: Download Production Files
        run: |
          Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=14pitMRkVMLIxxSlTF-49AFg6haqGamCa" -OutFile gil_cms_prod.zip
          Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=14pitMRkVMLIxxSlTF-49AFg6haqGamCa" -OutFile gil_cms_https_proxy.zip

      - name: Set up Environment Variables
        run: |
          echo DATABASE_URL='sqlserver://localhost:1433;database=<dbname>;integratedSecurity=false;username=<dbusername>;password=<dbpassword>;trustServerCertificate=true;' >> $GITHUB_ENV
          echo AUTH_TYPE=ldap >> $GITHUB_ENV
          echo PORT=80 >> $GITHUB_ENV
          echo SQLSERVER_HOST=localhost >> $GITHUB_ENV
          echo SQLSERVER_USER=cmsadmin2 >> $GITHUB_ENV
          echo SQLSERVER_PASSWORD=cmsadmin2 >> $GITHUB_ENV
          echo SQLSERVER_DB_NAME=gil_cms2 >> $GITHUB_ENV
          echo SQLSERVER_DB_BACKUP_PATH=C:/sqlserver_Backup >> $GITHUB_ENV
          echo JWT_SECRET=Arizon123 >> $GITHUB_ENV
          echo SUPER_ADMIN_USERNAME=super-admin >> $GITHUB_ENV
          echo SUPER_ADMIN_PASSWORD=Arizon@123 >> $GITHUB_ENV
          echo PRISMA_OPTIMIZE=N >> $GITHUB_ENV
          echo PRISMA_LOGGING=Y >> $GITHUB_ENV
          echo NODE_ENV=production >> $GITHUB_ENV
          echo SEED=Y >> $GITHUB_ENV
          echo SEED_BLOCK=Y >> $GITHUB_ENV

      - name: Set Up and Migrate Database
        run: npx prisma db push
        working-directory: ./gil_cms_prod             
     
      - name: Seed Database
        run: |
          cd ${{ github.workspace }}/gil_cms_prod
          set SEED=Y
          set SEED_BLOCK=Y
          node src/index.js
          set SEED=N
          set SEED_BLOCK=N

      - name: Start Backend with PM2
        run: |
          cd ${{ github.workspace }}/gil_cms_prod
          pm2 start src/index.js --name "cms-backend"

      - name: Start Proxy with PM2
        run: |
          cd ${{ github.workspace }}/gil_cms_https_proxy
          pm2 start server.js --name "cms-proxy"

      - name: Monitor Applications with PM2
        run: pm2 monit

      - name: Backup
        run: echo "Regularly backup your database and important configuration files"

      - name: Update Dependencies
        run: echo "Regularly update your application dependencies and Windows Server for security patches"

      - name: Post-Deployment Tasks
        run: echo "Post-deployment maintenance tasks"

      - name: Final Tasks
        run: echo "Final cleanup or notification tasks"
