name: CMS
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: windows-latest
    env:
      nodeVersion: 14.x
      artifactName: production-files
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nodeVersion }}

  # - name: Install Build Tools for Node.js
     #   run: npm install -g windows-build-tools

      - name: Install PM2
        run: npm install pm2 -g

      - name: Download Production Files
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: ${{ github.workspace }}

      - name: Setup and Migrate Database
        run: |
          cd ${{ github.workspace }}/gil_cms_prod
          npm install
          npx prisma db push

      - name: Seed Database
        run: |
          cd ${{ github.workspace }}/gil_cms_prod
          set SEED=Y
          set SEED_BLOCK=Y
          node src/index.js
          set SEED=N
          set SEED_BLOCK=N

      - name: Start Backend with PM2
        run: |
          cd ${{ github.workspace }}/gil_cms_prod
          pm2 start src/index.js --name "cms-backend"

      - name: Start Proxy with PM2
        run: |
          cd ${{ github.workspace }}/gil_cms_https_proxy
          pm2 start server.js --name "cms-proxy"

      - name: Monitor Applications with PM2
        run: pm2 monit

      - name: Backup
        run: echo "Regularly backup your database and important configuration files"

      - name: Update Dependencies
        run: echo "Regularly update your application dependencies and Windows Server for security patches"

      - name: Post-Deployment Tasks
        run: echo "Post-deployment maintenance tasks"

      - name: Final Tasks
        run: echo "Final cleanup or notification tasks"
